import * as THREE from 'three';
import { OBJExporter as ThreeOBJExporter } from 'three/examples/jsm/exporters/OBJExporter.js';
import { exportFbx } from 'three-js-fbx-exporter';
import type { BlockbenchTexture } from './BlockbenchParser';

/**
 * Downloads text content as a file in the browser.
 */
function downloadTextFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const link = document.createElement('a');
  link.style.display = 'none';
  document.body.appendChild(link);
  
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

/**
 * Downloads a binary buffer as a file in the browser.
 */
function downloadBinaryFile(data: Uint8Array, filename: string) {
  const blob = new Blob([data.buffer as ArrayBuffer], { type: 'application/octet-stream' });
  const link = document.createElement('a');
  link.style.display = 'none';
  document.body.appendChild(link);

  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();

  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

/**
 * Downloads a texture image as a PNG file.
 */
function downloadTextureImage(image: HTMLImageElement, filename: string): Promise<void> {
  return new Promise((resolve) => {
    const canvas = document.createElement('canvas');
    canvas.width = image.naturalWidth || image.width || 64;
    canvas.height = image.naturalHeight || image.height || 64;
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      resolve();
      return;
    }
    
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(image, 0, 0);
    
    canvas.toBlob((blob) => {
      if (!blob) {
        resolve();
        return;
      }
      const link = document.createElement('a');
      link.style.display = 'none';
      document.body.appendChild(link);
      
      link.href = URL.createObjectURL(blob);
      link.download = filename;
      link.click();
      
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
      resolve();
    }, 'image/png');
  });
}

/**
 * Exports a parsed Blockbench model group to OBJ + MTL + PNG.
 */
export function exportToOBJ(
  modelGroup: THREE.Group,
  textures: BlockbenchTexture[],
  filenamePrefix: string
): Promise<void> {
  return new Promise(async (resolve, reject) => {
    try {
      const exporter = new ThreeOBJExporter();
      const rawObj = exporter.parse(modelGroup);
      
      const objFilename = `${filenamePrefix}.obj`;
      const mtlFilename = `${filenamePrefix}.mtl`;
      
      // Prepend mtllib reference to obj
      const objText = `mtllib ${mtlFilename}\n${rawObj}`;
      
      // Build the MTL text dynamically based on the textures
      let mtlText = `# Blockbench Model - Material Template Library\n# Generated by SkinBridge Blockbench Converter\n\n`;
      
      // Add transparent material definition if used
      mtlText += `newmtl mat_transparent\n`;
      mtlText += `Ka 0.000 0.000 0.000\n`;
      mtlText += `Kd 0.000 0.000 0.000\n`;
      mtlText += `Ks 0.000 0.000 0.000\n`;
      mtlText += `Ns 10.000\n`;
      mtlText += `d 0.000\n`;
      mtlText += `illum 2\n\n`;

      const texturesToDownload: { name: string; img: HTMLImageElement }[] = [];

      textures.forEach((tex) => {
        const matName = `mat_${tex.name || tex.id}`;
        const rawTexName = tex.name || `${tex.id}.png`;
        const texName = `skinbridge_${rawTexName}`;
        
        mtlText += `newmtl ${matName}\n`;
        mtlText += `Ka 1.000 1.000 1.000\n`;
        mtlText += `Kd 1.000 1.000 1.000\n`;
        mtlText += `Ks 0.000 0.000 0.000\n`;
        mtlText += `Ns 10.000\n`;
        mtlText += `d 1.000\n`;
        mtlText += `illum 2\n`;
        mtlText += `map_Kd ${texName}\n\n`;

        if (tex.loadedImage) {
          texturesToDownload.push({ name: texName, img: tex.loadedImage });
        }
      });
      
      // Download OBJ file
      downloadTextFile(objText, objFilename, 'text/plain');
      
      // Download MTL file after 200ms
      await new Promise(r => setTimeout(r, 200));
      downloadTextFile(mtlText, mtlFilename, 'text/plain');
      
      // Download textures after 400ms sequentially
      for (const texInfo of texturesToDownload) {
        await new Promise(r => setTimeout(r, 200));
        await downloadTextureImage(texInfo.img, texInfo.name);
      }
      
      resolve();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Exports a parsed Blockbench model group to a binary FBX file with embedded textures.
 */
export function exportToFBX(
  modelGroup: THREE.Group,
  filenamePrefix: string
): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      const fbxBytes = exportFbx(modelGroup, {
        format: 'binary',
        target: 'blender',
        embedTextures: true,
        onWarning: (warning) => {
          console.warn('[FBX Export Warning]', warning.message || warning.code);
        },
      });

      downloadBinaryFile(fbxBytes, `${filenamePrefix}.fbx`);
      resolve();
    } catch (err) {
      reject(err);
    }
  });
}
