import * as THREE from 'three';
import { OBJExporter as ThreeOBJExporter } from 'three/examples/jsm/exporters/OBJExporter.js';

/**
 * Downloads text content as a file in the browser.
 */
function downloadTextFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const link = document.createElement('a');
  link.style.display = 'none';
  document.body.appendChild(link);
  
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

/**
 * Downloads the skin image as a PNG file (textura.png).
 */
function downloadSkinImage(image: HTMLImageElement, filename: string): Promise<void> {
  return new Promise((resolve) => {
    const canvas = document.createElement('canvas');
    canvas.width = 256;
    canvas.height = 256;
    const ctx = canvas.getContext('2d');
    if (!ctx) { resolve(); return; }
    
    // Scale the 64x64 texture to 256x256 using NEAREST NEIGHBOR interpolation
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(image, 0, 0, 64, 64, 0, 0, 256, 256);
    
    canvas.toBlob((blob) => {
      if (!blob) { resolve(); return; }
      const link = document.createElement('a');
      link.style.display = 'none';
      document.body.appendChild(link);
      
      link.href = URL.createObjectURL(blob);
      link.download = filename;
      link.click();
      
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
      resolve();
    }, 'image/png');
  });
}

/**
 * Exports the Three.js head model to OBJ + MTL + PNG format.
 * 
 * Downloads three files:
 * - cabeza.obj  (geometry with UV, normals, material references)
 * - cabeza.mtl  (material definitions linking to textura.png)
 * - textura.png (the original skin texture)
 * 
 * @param input The THREE.Object3D (head group) to export
 * @param skinImage The HTMLImageElement containing the original skin
 */
export function exportToOBJ(input: THREE.Object3D, skinImage: HTMLImageElement): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      // Assign proper material names so OBJExporter writes `usemtl` statements
      input.traverse((child) => {
        if (child instanceof THREE.Mesh) {
          const mat = child.material;
          const matName = child.name === 'Head' ? 'HeadMaterial' : 'OverlayMaterial';
          
          if (Array.isArray(mat)) {
            mat.forEach((m) => { if (m) m.name = matName; });
          } else if (mat) {
            mat.name = matName;
          }
        }
      });

      const exporter = new ThreeOBJExporter();
      const rawObj = exporter.parse(input);
      
      // Prepend the mtllib reference so importers can find cabeza.mtl
      const objText = `mtllib cabeza.mtl\n${rawObj}`;
      
      // Generate MTL content with proper material definitions
      const mtlText = `# Minecraft Head - Material Template Library
# Generated by Minecraft 3D Head Creator

newmtl HeadMaterial
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.000 0.000 0.000
Ns 10.000
d 1.000
illum 2
map_Kd textura.png

newmtl OverlayMaterial
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.000 0.000 0.000
Ns 10.000
d 1.000
illum 2
map_Kd textura.png
map_d textura.png
`;

      // Download all three files with small delays to avoid browser blocking
      downloadTextFile(objText, 'cabeza.obj', 'text/plain');
      
      setTimeout(() => {
        downloadTextFile(mtlText, 'cabeza.mtl', 'text/plain');
      }, 200);

      setTimeout(async () => {
        await downloadSkinImage(skinImage, 'textura.png');
        resolve();
      }, 400);

    } catch (error) {
      reject(error);
    }
  });
}
